#!/usr/bin/python
import argparse
import yaml
import subprocess
import time
import os

## Process arguments
parser = argparse.ArgumentParser(description='SVP Virtual Machine Manager')
parser.add_argument('--start', action='store', dest='startVM', help='Start Virtual Machine')
parser.add_argument('--stop', action='store', dest='stopVM', help='Stop Virtual Machine')
parser.add_argument('--restart', action='store', dest='restartVM', help='Restart Virtual Machine')
parser.add_argument('--index', action='store_true', dest='index', help='Index all VMs')
args = parser.parse_args()

def check_pid(pid):        
    """ Check For the existence of a unix pid. """
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    else:
        return True

def startVM(start):
    print "Starting virtual machine",start

    configFile = ("/etc/cubyte/vms/{0}.yml".format(start))
    with open(configFile, 'r') as ymlfile:
        cfg = yaml.load(ymlfile)

    UUID = cfg['server']['UUID']
    mac0 = cfg['server']['mac0']
    int0 = cfg['server']['int0']
    net0 = '{0}{1}'.format(int0,UUID)
    memory = cfg['server']['memory']
    smp = cfg['server']['smp']
    servername =  cfg['server']['servername']
    lvname = cfg['server']['lvname']
    iso = cfg['server']['iso']
    disktype = cfg['server']['disktype']

    createNetwork = 'ip link add link eth0 name macvtap{0} type macvtap'.format(UUID)
    p1 = subprocess.Popen(createNetwork, shell=True, stdout=subprocess.PIPE)
    p1.wait();
    startNetwork = 'ip link set macvtap{0} address {1} up'.format(UUID,mac0)
    p2 = subprocess.Popen(startNetwork, shell=True, stdout=subprocess.PIPE)
    p2.wait();

    #Get correct tap device
    step1 = ['ip', 'a']
    step2 = ['grep', net0]
    step3 = ['awk', '{{print $1}}']
    s1 = subprocess.Popen(step1, stdout=subprocess.PIPE)
    s2 = subprocess.Popen(step2, stdin=s1.stdout, stdout=subprocess.PIPE)
    s3 = subprocess.Popen(step3, stdin=s2.stdout, stdout=subprocess.PIPE).stdout
    tapOutput = s3.read()
    tap = tapOutput[:-2]

    startMachine = '/usr/bin/qemu-system-x86_64 -daemonize --enable-kvm -cpu host -m {0} -smp {1} -name {2} -vnc 0.0.0.0:{3} -monitor unix:/tmp/{2}.qemu,server,nowait -pidfile /tmp/{2}.pid -drive format=raw,file=/dev/mapper/vmdisks-{4},if={5} -net nic,netdev=net0,model=virtio,macaddr={6} -netdev tap,id=net0,fd=3 3<>/dev/tap{7} -cdrom /storage/ISO/{8}'.format(memory,smp,servername,UUID,lvname,disktype,mac0,tap,iso)
    p3 = subprocess.Popen(startMachine, shell=True, stdout=subprocess.PIPE)
    p3.wait();

def stopVM(stop):
    print "Stopping virtual machine",stop
    
    configFile = ("/etc/cubyte/vms/{0}.yml".format(stop))
    with open(configFile, 'r') as ymlfile:
        cfg = yaml.load(ymlfile)

    UUID = cfg['server']['UUID']
    servername =  cfg['server']['servername']
    qemuFile = '/tmp/{0}.qemu'.format(servername)
    qemuPID = '/tmp/{0}.pid'.format(servername)

    #Shutdown machine
    step1 = ['echo', 'system_powerdown']
    step2 = ['socat', '-', qemuFile]
    s1 = subprocess.Popen(step1, stdout=subprocess.PIPE)
    s2 = subprocess.Popen(step2, stdin=s1.stdout, stdout=subprocess.PIPE).stdout
    output = s2.read()
    print output

    with open(qemuPID, 'r') as myfile:
        pidstr=myfile.read().replace('\n', '')
    pid = int(pidstr)

    state = True
    while state == True:
        output = check_pid(pid)
        if output == False:
            state = False
            print("Server {0} is not running".format(servername))
            #Delete network interface
            print "Stopping network interface"
            stopNetwork = 'ip link set macvtap{0} down'.format(UUID)
            p1 = subprocess.Popen(stopNetwork, shell=True, stdout=subprocess.PIPE)
            p1.wait();
            print "Deleting network interface"
            deleteNetwork = 'ip link del dev macvtap{0}'.format(UUID)
            p2 = subprocess.Popen(deleteNetwork, shell=True, stdout=subprocess.PIPE)
            p2.wait();
        else:
            print("Server {0} is still running".format(servername))
        time.sleep(2)

if args.startVM:
    startVM(start=args.startVM)
if args.stopVM:
    stopVM(stop=args.stopVM)
if args.restartVM:
    print("Restarting Virtual Machine {0}".format(args.restartVM))
    stopVM(stop=args.restartVM)
    startVM(start=args.restartVM)

if args.index:
    print "Indexing virtual machines"

